version: "3.9"

services:
  backend:
    build:
      context: ./
    container_name: chronos-backend
    expose:
      - "8080"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: chronos-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
