version: "3.9"

services:
  backend:
    build:
      context: ./
    container_name: chronos-backend
    expose:
      - "8080"
    ports:
      - "8080:8080"  # optional: expose externally for testing
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: chronos-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
